// source: hello.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() { return this || window || global || self || Function('return this')(); }).call(null);

goog.exportSymbol('proto.NetworkStatus', null, global);
goog.exportSymbol('proto.ServerStatusRequest', null, global);
goog.exportSymbol('proto.ServerStatusResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ServerStatusRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ServerStatusRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ServerStatusRequest.displayName = 'proto.ServerStatusRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ServerStatusResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.ServerStatusResponse.repeatedFields_, null);
};
goog.inherits(proto.ServerStatusResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ServerStatusResponse.displayName = 'proto.ServerStatusResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.NetworkStatus = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.NetworkStatus, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.NetworkStatus.displayName = 'proto.NetworkStatus';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ServerStatusRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.ServerStatusRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ServerStatusRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ServerStatusRequest.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ServerStatusRequest}
 */
proto.ServerStatusRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ServerStatusRequest;
  return proto.ServerStatusRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ServerStatusRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ServerStatusRequest}
 */
proto.ServerStatusRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ServerStatusRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ServerStatusRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ServerStatusRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ServerStatusRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.ServerStatusResponse.repeatedFields_ = [5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ServerStatusResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.ServerStatusResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ServerStatusResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ServerStatusResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    uptime: jspb.Message.getFieldWithDefault(msg, 1, 0),
    memory: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
    disk: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
    cpu: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0),
    loadList: (f = jspb.Message.getRepeatedFloatingPointField(msg, 5)) == null ? undefined : f,
    network: (f = msg.getNetwork()) && proto.NetworkStatus.toObject(includeInstance, f),
    currentNetwork: (f = msg.getCurrentNetwork()) && proto.NetworkStatus.toObject(includeInstance, f),
    ping: jspb.Message.getFieldWithDefault(msg, 8, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ServerStatusResponse}
 */
proto.ServerStatusResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ServerStatusResponse;
  return proto.ServerStatusResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ServerStatusResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ServerStatusResponse}
 */
proto.ServerStatusResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setUptime(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setMemory(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setDisk(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setCpu(value);
      break;
    case 5:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedDouble() : [reader.readDouble()]);
      for (var i = 0; i < values.length; i++) {
        msg.addLoad(values[i]);
      }
      break;
    case 6:
      var value = new proto.NetworkStatus;
      reader.readMessage(value,proto.NetworkStatus.deserializeBinaryFromReader);
      msg.setNetwork(value);
      break;
    case 7:
      var value = new proto.NetworkStatus;
      reader.readMessage(value,proto.NetworkStatus.deserializeBinaryFromReader);
      msg.setCurrentNetwork(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setPing(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ServerStatusResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ServerStatusResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ServerStatusResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ServerStatusResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUptime();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getMemory();
  if (f !== 0.0) {
    writer.writeDouble(
      2,
      f
    );
  }
  f = message.getDisk();
  if (f !== 0.0) {
    writer.writeDouble(
      3,
      f
    );
  }
  f = message.getCpu();
  if (f !== 0.0) {
    writer.writeDouble(
      4,
      f
    );
  }
  f = message.getLoadList();
  if (f.length > 0) {
    writer.writePackedDouble(
      5,
      f
    );
  }
  f = message.getNetwork();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.NetworkStatus.serializeBinaryToWriter
    );
  }
  f = message.getCurrentNetwork();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.NetworkStatus.serializeBinaryToWriter
    );
  }
  f = message.getPing();
  if (f !== 0) {
    writer.writeUint64(
      8,
      f
    );
  }
};


/**
 * optional uint64 uptime = 1;
 * @return {number}
 */
proto.ServerStatusResponse.prototype.getUptime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.ServerStatusResponse} returns this
 */
proto.ServerStatusResponse.prototype.setUptime = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional double memory = 2;
 * @return {number}
 */
proto.ServerStatusResponse.prototype.getMemory = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.ServerStatusResponse} returns this
 */
proto.ServerStatusResponse.prototype.setMemory = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional double disk = 3;
 * @return {number}
 */
proto.ServerStatusResponse.prototype.getDisk = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.ServerStatusResponse} returns this
 */
proto.ServerStatusResponse.prototype.setDisk = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional double cpu = 4;
 * @return {number}
 */
proto.ServerStatusResponse.prototype.getCpu = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.ServerStatusResponse} returns this
 */
proto.ServerStatusResponse.prototype.setCpu = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * repeated double load = 5;
 * @return {!Array<number>}
 */
proto.ServerStatusResponse.prototype.getLoadList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 5));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.ServerStatusResponse} returns this
 */
proto.ServerStatusResponse.prototype.setLoadList = function(value) {
  return jspb.Message.setField(this, 5, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.ServerStatusResponse} returns this
 */
proto.ServerStatusResponse.prototype.addLoad = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 5, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.ServerStatusResponse} returns this
 */
proto.ServerStatusResponse.prototype.clearLoadList = function() {
  return this.setLoadList([]);
};


/**
 * optional NetworkStatus network = 6;
 * @return {?proto.NetworkStatus}
 */
proto.ServerStatusResponse.prototype.getNetwork = function() {
  return /** @type{?proto.NetworkStatus} */ (
    jspb.Message.getWrapperField(this, proto.NetworkStatus, 6));
};


/**
 * @param {?proto.NetworkStatus|undefined} value
 * @return {!proto.ServerStatusResponse} returns this
*/
proto.ServerStatusResponse.prototype.setNetwork = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ServerStatusResponse} returns this
 */
proto.ServerStatusResponse.prototype.clearNetwork = function() {
  return this.setNetwork(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ServerStatusResponse.prototype.hasNetwork = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional NetworkStatus current_network = 7;
 * @return {?proto.NetworkStatus}
 */
proto.ServerStatusResponse.prototype.getCurrentNetwork = function() {
  return /** @type{?proto.NetworkStatus} */ (
    jspb.Message.getWrapperField(this, proto.NetworkStatus, 7));
};


/**
 * @param {?proto.NetworkStatus|undefined} value
 * @return {!proto.ServerStatusResponse} returns this
*/
proto.ServerStatusResponse.prototype.setCurrentNetwork = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ServerStatusResponse} returns this
 */
proto.ServerStatusResponse.prototype.clearCurrentNetwork = function() {
  return this.setCurrentNetwork(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ServerStatusResponse.prototype.hasCurrentNetwork = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional uint64 ping = 8;
 * @return {number}
 */
proto.ServerStatusResponse.prototype.getPing = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.ServerStatusResponse} returns this
 */
proto.ServerStatusResponse.prototype.setPing = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.NetworkStatus.prototype.toObject = function(opt_includeInstance) {
  return proto.NetworkStatus.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.NetworkStatus} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.NetworkStatus.toObject = function(includeInstance, msg) {
  var f, obj = {
    upload: jspb.Message.getFieldWithDefault(msg, 1, ""),
    download: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.NetworkStatus}
 */
proto.NetworkStatus.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.NetworkStatus;
  return proto.NetworkStatus.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.NetworkStatus} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.NetworkStatus}
 */
proto.NetworkStatus.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUpload(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDownload(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.NetworkStatus.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.NetworkStatus.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.NetworkStatus} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.NetworkStatus.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUpload();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDownload();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string upload = 1;
 * @return {string}
 */
proto.NetworkStatus.prototype.getUpload = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.NetworkStatus} returns this
 */
proto.NetworkStatus.prototype.setUpload = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string download = 2;
 * @return {string}
 */
proto.NetworkStatus.prototype.getDownload = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.NetworkStatus} returns this
 */
proto.NetworkStatus.prototype.setDownload = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


goog.object.extend(exports, proto);
